import "./globals.css";
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['200','400', '500', '600', '700'],  
  variable: '--font-montserrat', 
});

 

export const metadata = {
  title: "Hadana",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo/icon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
